const $ = (s,root=document)=>root.querySelector(s);
const $$ = (s,root=document)=>[...root.querySelectorAll(s)];
$('#year').textContent=new Date().getFullYear();
const nav=$('#nav');$('#menuToggle').addEventListener('click',()=>nav.classList.toggle('open'));$$('#nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const planner=$('#planner'),body=$('#stepBody'),title=$('#plannerTitle'),desc=$('#stepDesc'),kicker=$('#stepKicker'),fill=$('#progressFill'),count=$('#stepCount'),pct=$('#progressPct'),back=$('#backBtn'),next=$('#nextBtn'),error=$('#plannerError');
const data={types:[],style:'',template:'',features:[],budget:'',details:'',name:'',email:'',instagram:''};let step=0,previewModal=null;
const typeOpts=['Business Website','Portfolio','Landing Page','E-commerce Website','AI-Powered Website','Website Redesign','Other'];
const styleOpts=[['Dark','dark','Moody, high contrast'],['Light','light','Bright and airy'],['Minimal','minimal','Simple and focused'],['Bold','bold','Expressive and vivid'],['Luxury / Premium','luxury','Refined and elegant'],['Modern','modern','Fresh and current'],['Not sure','unsure','Suggest a direction']];
const templates=[['Business','business','Clear, confident, service-led'],['Creative','creative','Expressive layouts and color'],['Portfolio','portfolio','Showcase work with focus'],['Modern SaaS','saas','Product-led and structured'],['Luxury','luxury','Premium, editorial feel'],['Minimal','minimal','Quiet, clean and simple']];
const featureOpts=['Contact Form','Gallery','Blog','Booking','Payments','AI Features','Animations','Other'];
const budgetOpts=['Under $100','$100–$250','$250–$500','$500–$1,000','$1,000+','Not sure yet'];
const steps=[
 ['LET’S GET STARTED','What are you looking to build?','Choose one or more options that fit your project.'],
 ['YOUR VISUAL DIRECTION','What style do you want?','Pick the visual direction you’re drawn to. You can change it later.'],
 ['A PLACE TO START','Choose a starting style','Select a template direction for inspiration. It can be customized.'],
 ['MAKE IT YOURS','What features do you need?','Choose all the features you may need.'],
 ['PROJECT RANGE','What is your approximate budget?','A rough range is enough. Choose “Not sure yet” if you’re undecided.'],
 ['TELL ME MORE','Tell me a little about your project.','Share the goal, audience, pages, inspiration, or anything else useful.'],
 ['LAST STEP','How can I reach you?','Add your contact details so I can follow up about the project.']
];
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function selected(arr,val){return arr.includes(val)?' selected':''}
function choice(label,selectedState,attrs=''){return `<button type="button" class="choice${selectedState?' selected':''}" ${attrs}><span class="check">${selectedState?'✓':''}</span><span>${escapeHtml(label)}</span></button>`}
function render(){
 const [k,t,d]=steps[step];kicker.textContent=k;title.textContent=t;desc.textContent=d;count.textContent=`STEP ${step+1} OF 7`;pct.textContent=`${Math.round((step+1)/7*100)}%`;fill.style.width=`${(step+1)/7*100}%`;back.style.visibility=step===0?'hidden':'visible';next.textContent=step===6?'Review Project →':'Continue →';error.textContent='';
 if(step===0){body.innerHTML=`<div class="choice-grid">${typeOpts.map(x=>choice(x,data.types.includes(x),`data-type="${escapeHtml(x)}"`)).join('')}</div>`;$$('[data-type]',body).forEach(b=>b.onclick=()=>{const v=b.dataset.type;data.types=data.types.includes(v)?data.types.filter(x=>x!==v):[...data.types,v];render();});}
 if(step===1){body.innerHTML=`<div class="style-grid">${styleOpts.map(([n,c,sub])=>`<button type="button" class="style-card${data.style===n?' selected':''}" data-style="${n}"><div class="style-preview ${c}"><i></i></div><span class="style-name">${n}<small>${sub}</small></span></button>`).join('')}</div>`;$$('[data-style]',body).forEach(b=>b.onclick=()=>{data.style=b.dataset.style;render();});}
 if(step===2){body.innerHTML=`<div class="template-grid">${templates.map(([n,c,sub])=>`<article class="template-card${data.template===n?' selected':''}"><div class="template-art ${c}"><i></i></div><div class="template-label">${n}</div><div class="template-actions"><button class="mini-btn" type="button" data-preview="${n}">Preview</button><button class="mini-btn use" type="button" data-use="${n}">${data.template===n?'Selected ✓':'Use This Style'}</button></div></article>`).join('')}</div>`;$$('[data-use]',body).forEach(b=>b.onclick=()=>{data.template=b.dataset.use;render();});$$('[data-preview]',body).forEach(b=>b.onclick=()=>showPreview(b.dataset.preview));}
 if(step===3){body.innerHTML=`<div class="feature-grid">${featureOpts.map(x=>choice(x,data.features.includes(x),`data-feature="${escapeHtml(x)}"`)).join('')}</div>`;$$('[data-feature]',body).forEach(b=>b.onclick=()=>{const v=b.dataset.feature;data.features=data.features.includes(v)?data.features.filter(x=>x!==v):[...data.features,v];render();});}
 if(step===4){body.innerHTML=`<div class="budget-grid">${budgetOpts.map(x=>choice(x,data.budget===x,`data-budget="${escapeHtml(x)}"`)).join('')}</div>`;$$('[data-budget]',body).forEach(b=>b.onclick=()=>{data.budget=b.dataset.budget;render();});}
 if(step===5){body.innerHTML=`<label class="field-label" for="projectDetails">PROJECT OVERVIEW</label><textarea id="projectDetails" class="field" placeholder="I’m looking to create a website for…">${escapeHtml(data.details)}</textarea>`;$('#projectDetails').addEventListener('input',e=>data.details=e.target.value);}
 if(step===6){body.innerHTML=`<div class="field-wrap"><label class="field-label" for="contactName">NAME *</label><input class="field" id="contactName" autocomplete="name" placeholder="Your name" value="${escapeHtml(data.name)}"></div><div class="field-wrap"><label class="field-label" for="contactEmail">EMAIL *</label><input class="field" id="contactEmail" type="email" autocomplete="email" placeholder="you@example.com" value="${escapeHtml(data.email)}"></div><div class="field-wrap"><label class="field-label" for="contactInstagram">INSTAGRAM (OPTIONAL)</label><input class="field" id="contactInstagram" placeholder="@username" value="${escapeHtml(data.instagram)}"></div><p style="font-size:10px;color:#777">Only provide contact details you’re comfortable sharing.</p>`;$('#contactName').oninput=e=>data.name=e.target.value;$('#contactEmail').oninput=e=>data.email=e.target.value;$('#contactInstagram').oninput=e=>data.instagram=e.target.value;}
}
function showPreview(name){const t=templates.find(x=>x[0]===name);previewModal=document.createElement('div');previewModal.className='template-preview-modal';previewModal.innerHTML=`<div class="preview-box"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:14px"><b>${escapeHtml(name)} inspiration</b><button class="close-planner" aria-label="Close preview">✕</button></div><div class="template-art ${t[1]}"><i></i></div><p>${escapeHtml(t[2])}. This is a visual direction preview; the final design can be tailored to your project.</p><button class="btn" data-pick="${escapeHtml(name)}">Use This Style →</button></div>`;document.body.appendChild(previewModal);$('.close-planner',previewModal).onclick=()=>previewModal.remove();previewModal.onclick=e=>{if(e.target===previewModal)previewModal.remove()};$('[data-pick]',previewModal).onclick=()=>{data.template=name;previewModal.remove();render();};}
function valid(){if(step===0&&!data.types.length)return'Choose at least one website type.';if(step===1&&!data.style)return'Choose a design style, or select “Not sure”.';if(step===2&&!data.template)return'Choose a starting template, or preview one first.';if(step===3&&!data.features.length)return'Select at least one feature (or choose Other).';if(step===4&&!data.budget)return'Choose a budget range or “Not sure yet”.';if(step===6){data.name=$('#contactName').value.trim();data.email=$('#contactEmail').value.trim();data.instagram=$('#contactInstagram').value.trim();if(!data.name)return'Please enter your name.';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email))return'Please enter a valid email address.';}return''}
back.onclick=()=>{if(step>0){step--;render();}};
next.onclick=()=>{const err=valid();if(err){error.textContent=err;return;}if(step<6){step++;render();}else renderSummary();};
function summaryRows(){return [['Website type',data.types.join(', ')],['Design style',data.style],['Template',data.template],['Features',data.features.join(', ')],['Budget',data.budget],['Project description',data.details||'Not provided'],['Name',data.name],['Email',data.email],['Instagram',data.instagram||'Not provided']];}
function renderSummary(){error.textContent = '';kicker.textContent='REVIEW YOUR DETAILS';title.textContent='Project Summary';desc.textContent='Check your selections before sending your project request.';count.textContent='REVIEW';pct.textContent='READY';fill.style.width='100%';back.style.visibility='visible';next.textContent='Send Project Request →';body.innerHTML=`<div class="summary"><div class="summary-head"><span>PROJECT SUMMARY</span><span>ASHVATH / INQUIRY</span></div>${summaryRows().map(([k,v])=>`<div class="summary-row"><strong>${k}</strong><span>${escapeHtml(v)}</span></div>`).join('')}</div><h3 style="font-size:22px;margin:26px 0 8px">Ready to start?</h3><p style="font-size:11px;color:#999;margin:0">Send your request using your email app, or reach me on Instagram.</p>`;next.onclick=sendRequest;}
function sendRequest(){const subject=encodeURIComponent('Portfolio project request — '+data.name);const message=encodeURIComponent('PROJECT REQUEST\\n\\n'+summaryRows().map(([k,v])=>k+': '+v).join('\\n')+'\\n\\nSent from Ashvath portfolio project planner.');const mailto=`mailto:ashvathnaik60@gmail.com?subject=${subject}&body=${message}`;body.insertAdjacentHTML('beforeend',`<div class="success-panel"><div class="success-icon">↗</div><h3>Ready to send your request?</h3><p>Your email app will open with the project details filled in. Press Send there to deliver it. This site cannot confirm email delivery.</p><div class="success-actions"><a class="btn" href="${mailto}">Open Email Draft ↗</a><a class="btn btn-ghost" href="https://www.instagram.com/Web_developer/" target="_blank" rel="noopener">Instagram ↗</a></div></div>`);next.style.display='none';back.style.display='none';}
function openPlanner(){planner.classList.add('open');planner.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';step=0;Object.assign(data,{types:[],style:'',template:'',features:[],budget:'',details:'',name:'',email:'',instagram:''});next.style.display='';back.style.display='';next.onclick=()=>{const err=valid();if(err){error.textContent=err;return;}if(step<6){step++;render();}else renderSummary();};render();}
function closePlanner(){planner.classList.remove('open');planner.setAttribute('aria-hidden','true');document.body.style.overflow='';if(previewModal){previewModal.remove();previewModal=null;}}
$$('.open-planner').forEach(b=>b.addEventListener('click',openPlanner));$('#closePlanner').onclick=closePlanner;planner.addEventListener('click',e=>{if(e.target===planner)closePlanner()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&planner.classList.contains('open'))closePlanner()});
render();
